// "use client";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Providers } from "./store/Provider";
import SearchInput from "./components/SearchInput";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "400", "500"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Eat Express",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} h-screen min-h-screen bg-light dark:bg-gray-dark`}
      >
        <Providers>
          <Navbar />
          <SearchInput />
          {children}
        </Providers>
      </body>
    </html>
  );
}
