// "use client";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Ubuntu } from "next/font/google";
import { Providers } from "./store/Provider";
import SearchInput from "./components/SearchInput";

const ubuntu = Ubuntu({
  weight: ["300", "400", "500"],
  subsets: ["latin"],
  variable: "--font-ubuntu",
});

export const metadata = {
  title: "Eat Express",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`h-screen min-h-screen bg-light dark:bg-gray-dark  ${ubuntu.className}`}
      >
        <Providers>
          <Navbar />
          <SearchInput />
          {children}
        </Providers>
      </body>
    </html>
  );
}
